[build-system]
requires = ["sip >=5, <6"]
build-backend = "sipbuild.api"

[tool.sip.metadata]
name = "pympinv1"
version = "0.1"
license = "MIT"

[tool.sip.bindings.pympinv1]
headers = ["mpinv.h"]
libraries = ["mpinv"]
include-dirs = ["mpinv"]
library-dirs = ["mpinv/bin"]
