[build-system]
requires = ["sip >=5, <6"]
build-backend = "sipbuild.api"

[tool.sip.metadata]
name = "pympinv2"
version = "0.1"
license = "MIT"

[tool.sip.bindings.pympinv2]
headers = ["mpinv.h"]
libraries = ["mpinv"]
include-dirs = ["src"]
library-dirs = ["bin"]
